### ISSUE TITLE
Feature request - Read from file

### ISSUE THREAD

**Issue by testbughub** [SaltyRiver/MMM-SimpleText#1]
As well as an option for time to re-read it.
I think this would make this module 10x better.
For example, instead of relying on other modules for values gathered from a temperature sensor, just read it from a file.

EDIT:
Just noticed after doing a fork that it already has a function to refresh, so you could just add it as an option.

**Comment by SaltyRiver** [comment]
Could be a handy feature yea. I am currently not really invested in the MagicMirror project, if I have some time in the future I will look into this. Feel free to commit changes though.

**Comment by testbughub** [comment]
I've never really played around with javascript/node, so I'm pretty much shooting in the dark right now trying to add it myself :P

**Comment by thefoster** [comment]
I'm surprised that this doesn't exist yet, it should be one of the simpler modules to create.
I'm definitely interested, too.

**Comment by SaltyRiver** [comment]
I will look further into implemented this within the next few days. Gonna update this issue once that's done

**Comment by testbughub** [comment]
Nice! Thanks!

**Comment by thefoster** [comment]
Yes, thanks for that effort!
I'm gonna use that for displaying custom fortune cookies (phrases), which a cron job writes to a file every day (fortune -a custom.dat.o >file), the existing MMM-Fortunes module doesn't work here and has a different scope/look either.

**Comment by SaltyRiver** [comment]
I have added the functionality to read the content from text files, aswell as to refresh the module every given amount of milliseconds. Make sure to read through the entire updated .readme. If you have further wishes for this module feel free to ask!

**Comment by testbughub** [comment]
Glorious! This will definitely be one of my most used plugins! Thank you for taking the time to implement this :)

**Comment by thefoster** [comment]
Great, thank you!
