### ISSUE TITLE
Read File with multiple lines 

### ISSUE THREAD

**Issue by williamsnash** [SaltyRiver/MMM-SimpleText#2]
I have a simple text doc with text on different lines. When I use SimpleText shows up as one big block. Is there a way to have it print out the different lines. I have included a example of that the file would look like
```
This would print on its own line
This would show right below it
```

**Comment by SaltyRiver** [comment]
This is currently not tested as this module was developed for one liners. I will look into implementing your feature wish within the next few days. I will update this issue once that's done.

**Comment by SaltyRiver** [comment]
I have updated the project to display linebreaks correctly. Your file should now work as intended. If you have any further problems regarding this please reopen the issue.

![grafik](https://user-images.githubusercontent.com/51451976/127025686-57bf005d-2128-40dc-b100-798b04468544.png)
