### ISSUE TITLE
Bouncing Refresh

### ISSUE THREAD

**Issue by mikeyounge** [SaltyRiver/MMM-SimpleText#6]
Hi. I have a weird issue when using the filePath parameter. I have the refreshMs set to '1000' so I get a refresh every second on a file that is constantly changing. It reads it fine and works as intended, but about once a minute, the refresh seems to "bounce' all the modules below it. It's like it is unloading padding 3 or 4 times and then adding it back. Then everything will be static and look fine. If I change the filePath to a text parameter and just have static text, the bouncing doesn't occur. The problem occurs if the file has text or not. If the file is empty, is it possible to have it remove any padding that the module is creating? I would rather have it look like the module is not there when no text is available.

EDIT: I discovered that my file wasn't totally 'empty'. There was a line break when it was 'empty'. So the module was loading the extra break, then deleting it, then loading it again. When the extra break was removed, the module shifted up to where I expected it and stopped bouncing. Not sure why it is handling the extra line break that way, but it is. It still bounces when there is text present tho. Even if there is no extra break.

**Comment by SaltyRiver** [comment]
Is this the behaviour you are describing? First line reads text from a file in a 1000ms interval, bottom two lines are static text  

https://github.com/SaltyRiver/MMM-SimpleText/assets/51451976/1b9aaae6-51f8-4b18-a931-a8f95d5e0963

**Comment by mikeyounge** [comment]
That is exactly what happens. I only have two lines that I’m printing, but that is how it looks

**Comment by SaltyRiver** [comment]
I will look into this and notify you when I have a solution

**Comment by SaltyRiver** [comment]
@mikeyounge I create a pull request which from my perspective fixes the issue. To make sure, could you check out branch **6-bouncing-refresh** locally to verify that your issue is solved?  
  
As you can see here, the bouncing does not appear anymore, even when the content of the file changes. Refresh interval is set to one second  

https://github.com/SaltyRiver/MMM-SimpleText/assets/51451976/67ce8626-b369-4c28-9ae3-d3d8f87c1132

**Comment by mikeyounge** [comment]
That seems to have fixed it. Thank you for taking a look. I'll mark this as closed.

On a slightly different topic, do you have any advice for running multiple instances of this module? They are stacked on each other in the region and will often compete for space. If one has a blank text file, it will write, then the other with text will write and it will flash on and off. I added classes to the config to make them distinct, but it doesn't help. If I comment one of the modules out, I get static text. Do I need to do the duplicate folder trick with this module?

```
     {
       module: 'MMM-SimpleText',
       classes: 'cacheStatus',
       position: 'middle_center',
       config: {
                 filePath: { 'value': 'cacheStatus.txt' },
                 refreshMs: { 'value': '1000' },
                 color: { 'value': 'white ' },
                 fontSize: { 'value': 'large' }
       }
     },
    {
       module: 'MMM-SimpleText',
       classes: 'backingStatus',
       position: 'middle_center',
       config: {
                 filePath: { 'value': 'backingStatus.txt' },
                 refreshMs: { 'value': '1000' },
                 color: { 'value': 'white ' }
       }
     },
```

**Comment by SaltyRiver** [comment]
I created a new issue from your question, to take a look at it later

**Comment by SaltyRiver** [comment]
@mikeyounge please take a look at the discussion here #8 and check out the current state of the main branch, if this is still relevant for you

**Comment by mikeyounge** [comment]
Works perfectly. Now I can remove my second folder! Thanks so much guys!On Aug 13, 2024, at 8:35 AM, SaltyRiver ***@***.***> wrote:﻿
@mikeyounge please take a look at the discussion here #8 and check out the current state of the main branch, if this is still relevant for you
