### ISSUE TITLE
multiple modules competing for space

### ISSUE THREAD

**Issue by SaltyRiver** [SaltyRiver/MMM-SimpleText#8]
That seems to have fixed it. Thank you for taking a look. I'll mark this as closed.

On a slightly different topic, do you have any advice for running multiple instances of this module? They are stacked on each other in the region and will often compete for space. If one has a blank text file, it will write, then the other with text will write and it will flash on and off. I added classes to the config to make them distinct, but it doesn't help. If I comment one of the modules out, I get static text. Do I need to do the duplicate folder trick with this module?

```
     {
       module: 'MMM-SimpleText',
       classes: 'cacheStatus',
       position: 'middle_center',
       config: {
                 filePath: { 'value': 'cacheStatus.txt' },
                 refreshMs: { 'value': '1000' },
                 color: { 'value': 'white ' },
                 fontSize: { 'value': 'large' }
       }
     },
    {
       module: 'MMM-SimpleText',
       classes: 'backingStatus',
       position: 'middle_center',
       config: {
                 filePath: { 'value': 'backingStatus.txt' },
                 refreshMs: { 'value': '1000' },
                 color: { 'value': 'white ' }
       }
     },
```

_Originally posted by @mikeyounge in https://github.com/SaltyRiver/MMM-SimpleText/issues/6#issuecomment-2061511152_

**Comment by Race666** [comment]
Same here. I also want to use the module twice. 
And for the second module definition the filePath property is ignored respectively the file of the second module is not reed. 

Simple example:

For first defintion the content of the file Vertretungsplan0.txt is shown correctly
For the second defintion only the text  'No file 1' is shown even if the file exists,

```

		// Integration Vertretungsplan
		{
			module: 'MMM-SimpleText',
			position: 'top_center',
			config: {
					refreshMs: {
						'value': '60000'
					},
					text: {
					  'value': 'No file 0'
					},
					filePath: {
						'value': 'Vertretungsplan0.txt'
					},
					fontURL: {
					  'value': 'Tahoma, Geneva, sans-serif'
					},
					fontSize: {
					  // 'value': 'xx-large'
					},
					fontStyle: {
					  'value': 'normal'
					},
					color: {
					  // 'value': '#008000'
					}
				}
		},
		// Integration Vertretungsplan
		{
			module: 'MMM-SimpleText',
			position: 'top_center',
			config: {
					refreshMs: {
						'value': '60000'
					},				
					text: {
					  'value': 'No file 1'
					},
					filePath: {
						'value': 'Vertretungsplan1.txt'
					},
					fontURL: {
					  'value': 'Tahoma, Geneva, sans-serif'
					},
					fontSize: {
					  // 'value': 'xx-large'
					},
					fontStyle: {
					  'value': 'normal'
					},
					color: {
					  // 'value': '#008000'
					}
				}
		},	
```


When I only insert one module (tried both definietion) all works as expected.

Any hints on how to use 2 definitions?´


Update: it seems both files are reed but the content is always shown in the first MMM-SimpleText. Means both definitions update only the first module.

It writes always to the first definition of ID MMM-SimpleText-content
```

if (this.config.filePath["value"] !== "") {
            var self = this;
            this.readFileContent(function (response) {
                self.config.fileContent["value"] = response.replace(/(?:\r\n|\r|\n)/g, '<br>');
                document.getElementById("MMM-SimpleText-content").innerHTML = self.config.fileContent["value"];
            });
        }
```

**Comment by Race666** [comment]
@SaltyRiver I've fixed the issue by adding a UniqueID Option https://github.com/Race666/MMM-SimpleText and send you a pull requested. May be you have a better idea on fixing the issue..... :-)

**Comment by SaltyRiver** [comment]
@Race666 no this was a solid solution, cant think of a better way to do this. maybe index based, but that would bring other problems. doing it by id seems good. thanks for your implementation
